# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.cache/wt [current_project]
set_property parent.project_path D:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files d:/Code/Verilog/inst_multicycle.coe
add_files -quiet D:/Code/Verilog/lcd_module.dcp
set_property used_in_implementation false [get_files D:/Code/Verilog/lcd_module.dcp]
read_verilog -library xil_defaultlib {
  D:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.srcs/sources_1/new/adder.v
  D:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.srcs/sources_1/new/alu.v
  D:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.srcs/sources_1/new/decode.v
  D:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.srcs/sources_1/new/exe.v
  D:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.srcs/sources_1/new/fetch.v
  D:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.srcs/sources_1/new/mem.v
  D:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.srcs/sources_1/new/multi_cycle_cpu.v
  D:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.srcs/sources_1/new/regfile.v
  D:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.srcs/sources_1/new/wb.v
  D:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.srcs/sources_1/new/multi_cycle_cpu_display.v
}
read_ip -quiet D:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.srcs/sources_1/ip/data_ram/data_ram.xci
set_property used_in_implementation false [get_files -all d:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.srcs/sources_1/ip/data_ram/data_ram_ooc.xdc]

read_ip -quiet d:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.srcs/sources_1/ip/inst_rom_1/inst_rom.xci
set_property used_in_implementation false [get_files -all d:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.srcs/sources_1/ip/inst_rom_1/inst_rom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.srcs/constrs_1/new/multi_cycle_cpu.xdc
set_property used_in_implementation false [get_files D:/Code/Verilog/7_multi_cycle_cpu/7_multi_cycle_cpu.srcs/constrs_1/new/multi_cycle_cpu.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top multi_cycle_cpu_display -part xc7a200tfbg676-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef multi_cycle_cpu_display.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file multi_cycle_cpu_display_utilization_synth.rpt -pb multi_cycle_cpu_display_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
