set_property PACKAGE_PIN AC23 [get_ports {num[3]}]
set_property PACKAGE_PIN AC22 [get_ports {num[2]}]
set_property PACKAGE_PIN AD24 [get_ports {num[1]}]
set_property PACKAGE_PIN AC21 [get_ports {num[0]}]
set_property PACKAGE_PIN Y6 [get_ports {num[7]}]
set_property PACKAGE_PIN AA7 [get_ports {num[6]}]
set_property PACKAGE_PIN W6 [get_ports {num[5]}]
set_property PACKAGE_PIN AB6 [get_ports {num[4]}]

set_property PACKAGE_PIN AC19  [get_ports {clk}]

set_property PACKAGE_PIN E26 [get_ports {scan_select[1]}]
set_property PACKAGE_PIN G25 [get_ports {scan_select[0]}]

set_property PACKAGE_PIN C4 [get_ports {seg7[7]}]
set_property PACKAGE_PIN A2 [get_ports {seg7[6]}]
set_property PACKAGE_PIN D4 [get_ports {seg7[5]}]
set_property PACKAGE_PIN E5 [get_ports {seg7[4]}]
set_property PACKAGE_PIN B4 [get_ports {seg7[3]}]
set_property PACKAGE_PIN B2 [get_ports {seg7[2]}]
set_property PACKAGE_PIN E6 [get_ports {seg7[1]}]
set_property PACKAGE_PIN C3 [get_ports {seg7[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {clk}]

set_property IOSTANDARD LVCMOS33 [get_ports {num[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {scan_select[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {scan_select[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg7[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg7[0]}]
